bubble: bubble_sort.cpp test.cpp test.h
	clear && g++ bubble_sort.cpp test.cpp -o sort_app && ./sort_app

shaker: shaker_sort.cpp test.cpp test.h
	clear && g++ shaker_sort.cpp test.cpp -o sort_app && ./sort_app

comb: comb_sort.cpp test.cpp test.h
	clear && g++ comb_sort.cpp test.cpp -o sort_app && ./sort_app

insertion: insertion_sort.cpp test.cpp test.h
	clear && g++ insertion_sort.cpp test.cpp -o sort_app && ./sort_app
