str_to_num.o: str_to_num.asm
	nasm -f elf64 -g -F dwarf str_to_num.asm
str_to_num-clean: 
	-rm str_to_num.o 

math.o: math.asm
	nasm -f elf64 -g -F dwarf math.asm
math-clean: 
	-rm math.o 

begin1: begin1.o str_to_num.o
	gcc -o begin1 begin1.o str_to_num.o -no-pie
begin1.o: begin1.asm
	nasm -f elf64 -g -F dwarf begin1.asm -l begin1.lst
begin1-clean: 
	-rm begin1.lst begin1.o begin1

begin2: begin2.o str_to_num.o
	gcc -o begin2 begin2.o str_to_num.o -no-pie
begin2.o: begin2.asm
	nasm -f elf64 -g -F dwarf begin2.asm -l begin2.lst
begin2-clean: 
	-rm begin2.lst begin2.o begin2

begin3: begin3.o str_to_num.o
	gcc -o begin3 begin3.o str_to_num.o -no-pie
begin3.o: begin3.asm
	nasm -f elf64 -g -F dwarf begin3.asm -l begin3.lst
begin3-clean: 
	-rm begin3.lst begin3.o begin3

begin4: begin4.o str_to_num.o
	gcc -o begin4 begin4.o str_to_num.o -no-pie
begin4.o: begin4.asm
	nasm -f elf64 -g -F dwarf begin4.asm -l begin4.lst
begin4-clean: 
	-rm begin4.lst begin4.o begin4

begin5: begin5.o str_to_num.o
	gcc -o begin5 begin5.o str_to_num.o -no-pie
begin5.o: begin5.asm
	nasm -f elf64 -g -F dwarf begin5.asm -l begin5.lst
begin5-clean: 
	-rm begin5.lst begin5.o begin5

begin6: begin6.o str_to_num.o
	gcc -o begin6 begin6.o str_to_num.o -no-pie
begin6.o: begin6.asm
	nasm -f elf64 -g -F dwarf begin6.asm -l begin6.lst
begin6-clean: 
	-rm begin6.lst begin6.o begin6

begin7: begin7.o str_to_num.o
	gcc -o begin7 begin7.o str_to_num.o -no-pie
begin7.o: begin7.asm
	nasm -f elf64 -g -F dwarf begin7.asm -l begin7.lst
begin7-clean: 
	-rm begin7.lst begin7.o begin7

begin8: begin8.o str_to_num.o
	gcc -o begin8 begin8.o str_to_num.o -no-pie
begin8.o: begin8.asm
	nasm -f elf64 -g -F dwarf begin8.asm -l begin8.lst
begin8-clean: 
	-rm begin8.lst begin8.o begin8

begin9: begin9.o str_to_num.o
	gcc -o begin9 begin9.o str_to_num.o -no-pie
begin9.o: begin9.asm
	nasm -f elf64 -g -F dwarf begin9.asm -l begin9.lst
begin9-clean: 
	-rm begin9.lst begin9.o begin9

begin10: begin10.o str_to_num.o
	gcc -o begin10 begin10.o str_to_num.o -no-pie
begin10.o: begin10.asm
	nasm -f elf64 -g -F dwarf begin10.asm -l begin10.lst
begin10-clean: 
	-rm begin10.lst begin10.o begin10

begin11: begin11.o str_to_num.o
	gcc -o begin11 begin11.o str_to_num.o -no-pie
begin11.o: begin11.asm
	nasm -f elf64 -g -F dwarf begin11.asm -l begin11.lst
begin11-clean: 
	-rm begin11.lst begin11.o begin11

begin12: begin12.o str_to_num.o
	gcc -o begin12 begin12.o str_to_num.o -no-pie
begin12.o: begin12.asm
	nasm -f elf64 -g -F dwarf begin12.asm -l begin12.lst
begin12-clean: 
	-rm begin12.lst begin12.o begin12

begin13: begin13.o str_to_num.o
	gcc -o begin13 begin13.o str_to_num.o -no-pie
begin13.o: begin13.asm
	nasm -f elf64 -g -F dwarf begin13.asm -l begin13.lst
begin13-clean: 
	-rm begin13.lst begin13.o begin13

begin14: begin14.o str_to_num.o
	gcc -o begin14 begin14.o str_to_num.o -no-pie
begin14.o: begin14.asm
	nasm -f elf64 -g -F dwarf begin14.asm -l begin14.lst
begin14-clean: 
	-rm begin14.lst begin14.o begin14

begin15: begin15.o str_to_num.o
	gcc -o begin15 begin15.o str_to_num.o -no-pie
begin15.o: begin15.asm
	nasm -f elf64 -g -F dwarf begin15.asm -l begin15.lst
begin15-clean: 
	-rm begin15.lst begin15.o begin15

begin16: begin16.o str_to_num.o
	gcc -o begin16 begin16.o str_to_num.o -no-pie
begin16.o: begin16.asm
	nasm -f elf64 -g -F dwarf begin16.asm -l begin16.lst
begin16-clean: 
	-rm begin16.lst begin16.o begin16

begin17: begin17.o str_to_num.o
	gcc -o begin17 begin17.o str_to_num.o -no-pie
begin17.o: begin17.asm
	nasm -f elf64 -g -F dwarf begin17.asm -l begin17.lst
begin17-clean: 
	-rm begin17.lst begin17.o begin17

begin18: begin18.o str_to_num.o
	gcc -o begin18 begin18.o str_to_num.o -no-pie
begin18.o: begin18.asm
	nasm -f elf64 -g -F dwarf begin18.asm -l begin18.lst
begin18-clean: 
	-rm begin18.lst begin18.o begin18

begin19: begin19.o str_to_num.o
	gcc -o begin19 begin19.o str_to_num.o -no-pie
begin19.o: begin19.asm
	nasm -f elf64 -g -F dwarf begin19.asm -l begin19.lst
begin19-clean: 
	-rm begin19.lst begin19.o begin19

begin20: begin20.o str_to_num.o
	gcc -o begin20 begin20.o str_to_num.o -no-pie
begin20.o: begin20.asm
	nasm -f elf64 -g -F dwarf begin20.asm -l begin20.lst
begin20-clean: 
	-rm begin20.lst begin20.o begin20

begin21: begin21.o str_to_num.o
	gcc -o begin21 begin21.o str_to_num.o -no-pie
begin21.o: begin21.asm
	nasm -f elf64 -g -F dwarf begin21.asm -l begin21.lst
begin21-clean: 
	-rm begin21.lst begin21.o begin21

begin22: begin22.o str_to_num.o
	gcc -o begin22 begin22.o str_to_num.o -no-pie
begin22.o: begin22.asm
	nasm -f elf64 -g -F dwarf begin22.asm -l begin22.lst
begin22-clean: 
	-rm begin22.lst begin22.o begin22

begin23: begin23.o str_to_num.o
	gcc -o begin23 begin23.o str_to_num.o -no-pie
begin23.o: begin23.asm
	nasm -f elf64 -g -F dwarf begin23.asm -l begin23.lst
begin23-clean: 
	-rm begin23.lst begin23.o begin23

begin24: begin24.o str_to_num.o
	gcc -o begin24 begin24.o str_to_num.o -no-pie
begin24.o: begin24.asm
	nasm -f elf64 -g -F dwarf begin24.asm -l begin24.lst
begin24-clean: 
	-rm begin24.lst begin24.o begin24

begin25: begin25.o str_to_num.o math.o
	gcc -o begin25 begin25.o str_to_num.o math.o -no-pie
begin25.o: begin25.asm
	nasm -f elf64 -g -F dwarf begin25.asm -l begin25.lst
begin25-clean: 
	-rm begin25.lst begin25.o begin25

begin26: begin26.o str_to_num.o math.o
	gcc -o begin26 begin26.o str_to_num.o math.o -no-pie
begin26.o: begin26.asm
	nasm -f elf64 -g -F dwarf begin26.asm -l begin26.lst
begin26-clean: 
	-rm begin26.lst begin26.o begin26

begin27: begin27.o str_to_num.o math.o
	gcc -o begin27 begin27.o str_to_num.o math.o -no-pie
begin27.o: begin27.asm
	nasm -f elf64 -g -F dwarf begin27.asm -l begin27.lst
begin27-clean: 
	-rm begin27.lst begin27.o begin27

begin28: begin28.o str_to_num.o math.o
	gcc -o begin28 begin28.o str_to_num.o math.o -no-pie
begin28.o: begin28.asm
	nasm -f elf64 -g -F dwarf begin28.asm -l begin28.lst
begin28-clean: 
	-rm begin28.lst begin28.o begin28

begin29: begin29.o str_to_num.o math.o
	gcc -o begin29 begin29.o str_to_num.o math.o -no-pie
begin29.o: begin29.asm
	nasm -f elf64 -g -F dwarf begin29.asm -l begin29.lst
begin29-clean: 
	-rm begin29.lst begin29.o begin29

begin30: begin30.o str_to_num.o math.o
	gcc -o begin30 begin30.o str_to_num.o math.o -no-pie
begin30.o: begin30.asm
	nasm -f elf64 -g -F dwarf begin30.asm -l begin30.lst
begin30-clean: 
	-rm begin30.lst begin30.o begin30

clean: str_to_num-clean math-clean begin1-clean begin2-clean begin3-clean \
	begin4-clean begin5-clean begin6-clean begin7-clean begin8-clean \
	begin9-clean begin10-clean begin11-clean begin12-clean begin13-clean \
	begin14-clean begin15-clean begin16-clean begin17-clean \
	begin18-clean begin19-clean begin20-clean begin21-clean begin22-clean \
	begin23-clean begin24-clean begin25-clean begin26-clean begin27-clean \
	begin28-clean begin29-clean begin30-clean